// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spphymvbrzyxqtbavets.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwcGh5bXZicnp5eHF0YmF2ZXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1ODA3NTQsImV4cCI6MjA1ODE1Njc1NH0.2aS-XMAsiYUR3aqE1cWaTOHDMnxE7L83VlNwXWVoiSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);